### PR TITLE
updatesocial

### PR DESCRIPTION
**Pull request by DrMoE77**
Social Media icons has been updated

### CODE REVIEW

**Review by jcarait — CHANGES_REQUESTED** [review]
Thanks Mohamed, it looks good.

Would you be able to get the latest files from main and put the images in /assets/images folder? Then update the src directory of images.

image

**Comment by DrMoE77** [comment]
> Thanks Mohamed, it looks good.
> 
> Would you be able to get the latest files from main and put the images in /assets/images folder? Then update the src directory of images.
> 
> image

Hi this was already 

> Social Media icons has been updated

**Comment by DrMoE77** [comment]
> Thanks Mohamed, it looks good.
> 
> Would you be able to get the latest files from main and put the images in /assets/images folder? Then update the src directory of images.
> 
> image

Task completed

**Review by jcarait — APPROVED** [review]
Nice, thanks Mohamed!

**Pull request merged**
